### ISSUE TITLE
NPE prevents to launch a SSS transition from a Team for Capella project

### ISSUE THREAD

**Issue by mPorhel** [eclipse-capella/capella-sss-transition#121]
While trying to launch a Subsytem transition from a Team for Capella connected project, I get the following error: 

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.resources.IFile.getProject()" because the return value of "org.polarsys.capella.common.helpers.EcoreUtil2.getFile(org.eclipse.emf.ecore.resource.Resource)" is null
    at org.polarsys.capella.transition.system2subsystem.ui.preferences.FilteredOutputModelRenderer$NoSourceProjectViewerFilter.<init>(FilteredOutputModelRenderer.java:25)
    at org.polarsys.capella.transition.system2subsystem.ui.preferences.FilteredOutputModelRenderer.getTargetProject(FilteredOutputModelRenderer.java:53)
    at org.polarsys.capella.transition.system2subsystem.ui.preferences.FilteredOutputModelRenderer.proceedBrowse(FilteredOutputModelRenderer.java:39)
    at org.polarsys.capella.common.flexibility.wizards.renderer.BrowseRenderer$1.widgetSelected(BrowseRenderer.java:88)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4026)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
    at org.eclipse.jface.window.Window.open(Window.java:799)
    at org.polarsys.capella.core.transition.common.ui.handlers.options.TransitionUIOptionsHandler.init(TransitionUIOptionsHandler.java:69)
    at org.polarsys.capella.core.transition.common.activities.InitializeTransitionActivity.initializeOptionsHandler(InitializeTransitionActivity.java:360)
    at org.polarsys.capella.core.transition.common.activities.InitializeTransitionActivity.initializeContext(InitializeTransitionActivity.java:131)
    at org.polarsys.capella.core.transition.system.activities.InitializeTransitionActivity.initializeContext(InitializeTransitionActivity.java:52)
    at org.polarsys.capella.transition.system2subsystem.activities.InitializeTransitionActivity.initializeContext(InitializeTransitionActivity.java:130)
    at org.polarsys.capella.transition.system2subsystem.crossphases.activities.InitializeTransitionActivity.initializeContext(InitializeTransitionActivity.java:40)
    at org.polarsys.capella.core.transition.common.activities.InitializeTransitionActivity._run(InitializeTransitionActivity.java:83)
    at org.polarsys.capella.core.transition.common.activities.AbstractActivity.run(AbstractActivity.java:105)
    at org.polarsys.capella.core.transition.common.transposer.ExtendedCadenceLauncher.cadence(ExtendedCadenceLauncher.java:177)
    at org.polarsys.capella.core.transition.common.transposer.ExtendedCadenceLauncher.cadence(ExtendedCadenceLauncher.java:163)
    at org.polarsys.capella.core.transition.common.transposer.ExtendedCadenceLauncher.cadence(ExtendedCadenceLauncher.java:105)
    at org.polarsys.capella.core.transition.common.launcher.ActivitiesLauncher.cadence(ActivitiesLauncher.java:259)
    at org.polarsys.capella.core.transition.common.launcher.ActivitiesLauncher.triggerActivities(ActivitiesLauncher.java:251)
    at org.polarsys.capella.core.transition.common.launcher.ActivitiesLauncher.triggerActivities(ActivitiesLauncher.java:192)
    at org.polarsys.capella.core.transition.common.launcher.TransposerLauncher.launch(TransposerLauncher.java:144)
    at org.polarsys.capella.core.transition.common.launcher.TransposerLauncher.run(TransposerLauncher.java:118)
    at org.polarsys.capella.core.transition.common.commands.LauncherCommand.performTransformation(LauncherCommand.java:41)
    at org.polarsys.capella.core.transition.common.commands.DefaultCommand.run(DefaultCommand.java:105)
    at org.polarsys.capella.common.ef.ExecutionManager$2.doExecute(ExecutionManager.java:129)
    at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
    at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
    at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
    at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:496)
    at org.polarsys.capella.common.ef.internal.command.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:150)
    at org.polarsys.capella.common.platform.sirius.ted.SemanticEditingDomainFactory$SemanticCommandStack.doExecute(SemanticEditingDomainFactory.java:277)
    at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
    at org.polarsys.capella.common.ef.ExecutionManager.executeReadWriteCommand(ExecutionManager.java:93)
    at org.polarsys.capella.common.ef.ExecutionManager.execute(ExecutionManager.java:68)
    at org.polarsys.capella.core.transition.common.commands.CommandHandler.execute(CommandHandler.java:84)
    at org.polarsys.capella.core.transition.common.commands.CommandHandler.execute(CommandHandler.java:61)
    at org.polarsys.capella.core.transition.common.ui.commands.CommandUIHandler.executeCommand(CommandUIHandler.java:55)
    at org.polarsys.capella.core.transition.common.ui.commands.CommandUIHandler$1.run(CommandUIHandler.java:36)
```

Steps to reproduce: 
* On a Team for Capella connected project
* Select a Physical Component
* Launch a transition from contextual menu with System to Subsystem Transition > Vertical > SA
* Try to select the target project in the opened wizard
  * error

Note: 
* while launching the transition from a local project, the Team for Capella connected present in the workspace are not proposed in potential target projects, as expected.  
* documentation of this add-on might be improved to make this limitation more visible.

**Comment by mPorhel** [comment]
Issue is in plugins/org.polarsys.capella.transition.system2subsystem.ui/src/org/polarsys/capella/transition/system2subsystem/ui/preferences/FilteredOutputModelRenderer.java.

NoSourceProjectViewerFilter does not check that the it gets a null result from org.polarsys.capella.common.helpers.EcoreUtil2::getFile. 

The target project candidates filtering to retain only the local Capella projects is done in _core/plugins/org.polarsys.capella.core.transition.system.ui/src/org/polarsys/capella/core/transition/system/ui/dialog/ProjectSelectionDialog.java_ when it looks for projects containing a xxxx.capella file.
